apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-chatbot-aug131 
  janus-idp.io/tekton: test-chatbot-aug131
  backstage.io/kubernetes-id: test-chatbot-aug131
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-chatbot-aug131
resources: 
- application-dev.yaml